---
- name: Deploy nfs
  hosts: all
  become: yes
  tasks:
  - include_role:
      name: stackhpc.nfs
    vars:
      nfs_enable:
        server: "{{ inventory_hostname in groups['login'] | first }}"
        clients: true
      nfs_server: "{{ groups['login'] | first }}"
      nfs_export: "/export/nfs"
      nfs_client_mnt_point: "/mnt/nfs"
  - include_role:
      name: stackhpc.openhpc
    vars:
      openhpc_cluster_name: "jg"
      openhpc_slurm_control_host: "{{ groups['login'] | first }}"
      openhpc_slurm_partitions:
        - batch:
          name: "batch"
      openhpc_slurm_conf:
         location: /mnt/nfs/etc/slurm/slurm.conf
         shared_fs: true
      openhpc_enable:
         control: "{{ inventory_hostname in groups['login'] }}"
         batch: "{{ inventory_hostname in groups['computes'] }}"
         runtime: true
