
# This file is all the variables needed by terraform to set up the cluster infra.

os_cloud: p3 # name in clouds.yaml

cluster_name: "jg"

compute:
    image_name: "CentOS7.8-OpenHPC"
    flavor_name: "compute-A"
    key_pair: "usual"
    networks:
     - "ilab"
    hostname_pattern: "sv-b17-u37"
    hostname_prefix: "jg-"

